mode: diffusion # 设定训练模式
layering: True # 是否使用 `LayeringUNet2dConditionModel`
logging_level: INFO

# 和路径有关的一系列参数
pretrained_model: ~/Desktop/stable-diffusion-2-1
control_model: ~/Desktop/controlnet-sd21-depth-diffusers
revision: null
output_dir: ~/Desktop/logs/diffusion
logging_dir: logging_dir
root_dir: /datasets/OPV2V/train

# 加载 checkpoint 的参数
# resume_file: ~/Desktop/logs/controlnet/checkpoint-0
# resume_file_det: ~/Desktop/logs/detection/checkpoint-0-det.pth

# 显存优化
# 显存优化方面的参数 (不包括 batch size, 虽然设置较小的 batch size 有助于降低显存占用)
use_8bit_adam: true
enable_xformers_memory_efficient_attention: true
gradient_checkpointing: true
allow_tf32: true
mixed_precision: bf16

batch_size: 1
train_epoches: 30
max_train_steps: null # 如果不为 null 则会在程序中用于替代 `train_epoches`
num_workers: 4
shuffle: true
gradient_accumulation_steps: 1

# 优化器有关参数 (大部分都是根据 `train_controlnet` 写的)
learning_rate: 5e-6
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-08

lr_scheduler: constant
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
set_grads_to_none: true
max_grad_norm: 1.0

# TODO: 这里的参数是否需要和 lift_splat_shoot_args 的参数一致
cav_lidar_range: &cav_lidar_range [-102.4, -51.2, -3, 102.4, 51.2, 1]
ratio: &ratio 0.4

# LiftSplatShoot 模型需要的参数
lift_splat_shoot_args:
  grid_conf:
      xbound: [-51.2, 51.2, 0.2]   # Limit the range of the x direction and divide the grids
      ybound: [-51.2, 51.2, 0.2]   # Limit the range of the y direction and divide the grids
      zbound: [-10, 10, 20.0]   # Limit the range of the z direction and divide the grids
      ddiscr: [2, 50, 48]
      mode: 'LID'
  data_aug_conf: # 数据增强所需的参数
      resize_lim: [0.65, 0.7]
      final_dim: [384, 512]
      rot_lim: [-3.6, 3.6]
      H: 600
      W: 800
      rand_flip: False
      bot_pct_lim: [0.0, 0.05]
      cams: ['camera0', 'camera1', 'camera2', 'camera3']
      Ncams: 4
  img_downsample: 8
  img_features: 128
  use_depth_gt: false
  # HEAL 配置文件这里是 true, 但是我们还没有加载 depth 数据, 所以这里先设置为 false
  # 还有一个考虑: 因为使用的是预训练模型, 所以实际上不需要深度信息作为监督信号
  depth_supervision: false
  camera_encoder: EfficientNet
  pretrained_model_path: ~/fleet/diff-cood/checkpoints/net_epoch25.pth

# 特征交换有关的参数
change_args:
  patch_size: 5
  strategy: random
